### ISSUE TITLE
please update root-zone trust-anchors in trust-anchors.conf file

### ISSUE THREAD

**Issue by RoyArends** [Metaswitch/calico-dnsmasq#4]
Users of your software that enable DNSSEC will not be able to validate DNS after October the 11th 2018.

Your repository contains a trust-anchors.conf file without the new DNSSEC trust-anchors:

trust-anchor=.,19036,8,2,49AAC11D7B6F6446702E54A1607371607A1A41855200FD2CE1CDDE32F24E8FB5

It should also include:

trust-anchor=.,20326,8,2,E06D44B80B8F1D39A95C0B0D7C65D08458E880409BBC683457104237C7F8EC8D

More information can be found at: https://www.icann.org/resources/pages/ksk-rollover

Please don’t hesitate to get in touch.

Warmly,

Roy Arends
ICANN

**Comment by ozdanborne** [comment]
@neiljerram do we still need this repo?

**Comment by nelljerram** [comment]
@RoyArends @caseydavenport I believe we don't actually need this change in our dnsmasq repo, because:

1. We do all of our builds from this repo without HAVE_DNSSEC defined.
2. Our dnsmasq builds are intended for DHCP server function only (for an OpenStack compute node providing DHCP to its VMs), and none of our packaging or deployment instructions configures the "dnssec" option.
3. From my code reading, I believe there could only possibly be a trust anchor issue if built with HAVE_DNSSEC and with the "dnssec" option specified at runtime.

In case you think we still have a problem here, please do let me know and reopen this issue.
